# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slice_sample_1d_cpp <- function(x0, y, tau, eta, w = 0.1, m = 100L, n_samps = 4000L, lower, upper) {
    .Call(`_gibbsTI_slice_sample_1d_cpp`, x0, y, tau, eta, w, m, n_samps, lower, upper)
}

bootstrap_coverage_cpp <- function(tau, alpha, B, eta, theta_hat, boots, n_samps_boot, burn_in_boot, w, m) {
    .Call(`_gibbsTI_bootstrap_coverage_cpp`, tau, alpha, B, eta, theta_hat, boots, n_samps_boot, burn_in_boot, w, m)
}

calibrate_eta_cpp <- function(y, tau, alpha = 0.1, eta0 = 1.0, B = 200L, max_iter = 15L, tol = 1e-3, c = 0.5, gamma = 0.75, n_samps_boot = 1000L, burn_in_boot = 200L, w = 0.1, m = 100L, verbose = TRUE) {
    .Call(`_gibbsTI_calibrate_eta_cpp`, y, tau, alpha, eta0, B, max_iter, tol, c, gamma, n_samps_boot, burn_in_boot, w, m, verbose)
}

sample_joint_cpp <- function(y, tau_lower, tau_upper, eta, n_samps = 4000L, burn_in = 1000L, prop_sd = 0.5) {
    .Call(`_gibbsTI_sample_joint_cpp`, y, tau_lower, tau_upper, eta, n_samps, burn_in, prop_sd)
}

bootstrap_coverage_content_cpp <- function(tl, tu, alpha, B, eta, boots, y_orig, n_samps_boot, burn_in_boot, prop_sd) {
    .Call(`_gibbsTI_bootstrap_coverage_content_cpp`, tl, tu, alpha, B, eta, boots, y_orig, n_samps_boot, burn_in_boot, prop_sd)
}

calibrate_eta_joint_content_cpp <- function(y, tau_lower, tau_upper, alpha = 0.1, eta0 = 1.0, B = 200L, max_iter = 15L, tol = 1e-3, c = 0.5, gamma = 0.75, prop_sd = 0.5, n_samps_boot = 1000L, burn_in_boot = 200L, verbose = TRUE) {
    .Call(`_gibbsTI_calibrate_eta_joint_content_cpp`, y, tau_lower, tau_upper, alpha, eta0, B, max_iter, tol, c, gamma, prop_sd, n_samps_boot, burn_in_boot, verbose)
}

sample_joint_quantile_cpp <- function(y, tau_lower, tau_upper, eta, n_samps = 4000L, burn_in = 1000L, prop_sd = 0.5) {
    .Call(`_gibbsTI_sample_joint_quantile_cpp`, y, tau_lower, tau_upper, eta, n_samps, burn_in, prop_sd)
}

bootstrap_coverage_quantile_cpp <- function(tl, tu, alpha, B, eta, theta_hat_vec, boots, n_samps_boot, burn_in_boot, prop_sd) {
    .Call(`_gibbsTI_bootstrap_coverage_quantile_cpp`, tl, tu, alpha, B, eta, theta_hat_vec, boots, n_samps_boot, burn_in_boot, prop_sd)
}

calibrate_eta_joint_quantile_cpp <- function(y, tau_lower, tau_upper, alpha = 0.1, eta0 = 1.0, B = 200L, max_iter = 15L, tol = 1e-3, c = 0.5, gamma = 0.75, prop_sd = 0.5, n_samps_boot = 1000L, burn_in_boot = 200L, verbose = TRUE) {
    .Call(`_gibbsTI_calibrate_eta_joint_quantile_cpp`, y, tau_lower, tau_upper, alpha, eta0, B, max_iter, tol, c, gamma, prop_sd, n_samps_boot, burn_in_boot, verbose)
}

