# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
slice_sample_1d_cpp <- function(x0, y, tau, eta, w = 0.1, m = 100L, n_samps = 4000L, lower, upper) {
    .Call(`_gibbsTI_slice_sample_1d_cpp`, x0, y, tau, eta, w, m, n_samps, lower, upper)
}

#' @export
bootstrap_coverage_cpp <- function(tau, alpha, B, eta, theta_hat, boots) {
    .Call(`_gibbsTI_bootstrap_coverage_cpp`, tau, alpha, B, eta, theta_hat, boots)
}

#' @export
calibrate_eta_cpp <- function(y, tau, alpha = 0.1, eta0 = 1.0, B = 200L, max_iter = 15L, tol = 1e-3, c = 0.5, gamma = 0.75, verbose = TRUE) {
    .Call(`_gibbsTI_calibrate_eta_cpp`, y, tau, alpha, eta0, B, max_iter, tol, c, gamma, verbose)
}

sample_joint_cpp <- function(y, tau_lower, tau_upper, eta, n_samps = 4000L, burn_in = 1000L) {
    .Call(`_gibbsTI_sample_joint_cpp`, y, tau_lower, tau_upper, eta, n_samps, burn_in)
}

bootstrap_coverage_content_cpp <- function(tl, tu, alpha, B, eta, boots, y_orig) {
    .Call(`_gibbsTI_bootstrap_coverage_content_cpp`, tl, tu, alpha, B, eta, boots, y_orig)
}

calibrate_eta_joint_content_cpp <- function(y, tau_lower, tau_upper, alpha = 0.1, eta0 = 1.0, B = 200L, max_iter = 15L, verbose = TRUE) {
    .Call(`_gibbsTI_calibrate_eta_joint_content_cpp`, y, tau_lower, tau_upper, alpha, eta0, B, max_iter, verbose)
}

sample_joint_quantile_cpp <- function(y, tau_lower, tau_upper, eta, n_samps = 4000L, burn_in = 1000L) {
    .Call(`_gibbsTI_sample_joint_quantile_cpp`, y, tau_lower, tau_upper, eta, n_samps, burn_in)
}

bootstrap_coverage_quantile_cpp <- function(tl, tu, alpha, B, eta, theta_hat_vec, boots) {
    .Call(`_gibbsTI_bootstrap_coverage_quantile_cpp`, tl, tu, alpha, B, eta, theta_hat_vec, boots)
}

calibrate_eta_joint_quantile_cpp <- function(y, tau_lower, tau_upper, alpha = 0.1, eta0 = 1.0, B = 200L, max_iter = 15L, tol = 1e-3, c = 0.5, gamma = 0.75, verbose = TRUE) {
    .Call(`_gibbsTI_calibrate_eta_joint_quantile_cpp`, y, tau_lower, tau_upper, alpha, eta0, B, max_iter, tol, c, gamma, verbose)
}

